version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
    container_name: pecunia-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - /home/app/frontend/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true 

  backend:
    build:
      context: ./backend
    container_name: pecunia-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env
